#! /bin/sh

umount -f /mnt/jffs2 > /dev/null

release.sh 1> /dev/null 2> /dev/null

#killall ctrg_m
killall -12 ctrg_m
#echo "ctrg_m Terminal!"

sleep 2

if [ $# -eq 0  ]; then
    busybox reboot -f
else
    busybox reboot $* -f
fi
